from supabase import create_client

url = "https://sywxhehahunevputgxdd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d3hoZWhhaHVuZXZwdXRneGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDQxNDEsImV4cCI6MjA3Mjg4MDE0MX0.SGNrmklPobim7-zb4zs78e2i2VRrmV84gV7DIl2m5s8"
supabase = create_client(url, key)

create table public.sales_transactions (
  transaction_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  product_id bigint not null references public.product_master(product_id),
  units_sold int not null,
  sale_price double precision not null,
  store_id bigint null,
  region text null,
  constraint sales_transactions_pkey primary key (transaction_id)
);
