# .streamlit/secrets.toml

GOOGLE_API_KEY = "AIzaSyCUIogApR_6yzIKxjf1hNN1eb5DCjb6q6Y"


# --- NEW: Supabase Service Key (for write access) ---
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d3hoZWhhaHVuZXZwdXRneGRkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzMwNDE0MSwiZXhwIjoyMDcyODgwMTQxfQ.uV4AsUuRMozIKxZMk4UKmkx0Y94akhC5vNZqsj_5EKw"

# Supabase API Credentials
SUPABASE_URL = "https://sywxhehahunevputgxdd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d3hoZWhhaHVuZXZwdXRneGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDQxNDEsImV4cCI6MjA3Mjg4MDE0MX0.SGNrmklPobim7-zb4zs78e2i2VRrmV84gV7DIl2m5s8"

# --- NEW DATABASE CREDENTIALS FROM DIRECT CONNECTION URI ---

DB_HOST="db.sywxhehahunevputgxdd.supabase.co"
DB_NAME="postgres"
DB_USER="postgres"
DB_PASSWORD="SarikaSameer@13"
DB_PORT="5432"