# .streamlit/secrets.toml

GOOGLE_API_KEY = "AIzaSyCUIogApR_6yzIKxjf1hNN1eb5DCjb6q6Y"


# --- NEW DATABASE CREDENTIALS FROM DIRECT CONNECTION URI ---

DB_HOST="db.sywxhehahunevputgxdd.supabase.co"
DB_NAME="postgres"
DB_USER="postgres"
DB_PASSWORD="Samarika@1302"
DB_PORT="5432"